abstract class RoutePath {
  static const String HOME_PAGE = "/home";
  static const String LOGIN_PAGE = '/login'; // 登录页
  static const String REGISTER_PAGE = '/register'; // 注册页
  static const String UPDATE_PASSWORD_PAGE = '/update_password'; // 修改密码页
  static const String SET_PASSWORD_PAGE = '/set_password'; // 忘记密码页
  static const String SETTING_PAGE = '/setting'; // 设置页
  static const String MY_INFO_PAGE = "/my_info"; // 用户信息
  static const String SEARCH_PAGE = "/search"; //
  static const String PHONE_CONTACTS_PAGE = "/phone_contacts"; //
  static const String WEBVIEW_PAGE = "/webview"; // WEB页面
  static const String LANGUAGE_PAGE = "/language"; // 语言页面
  static const String ACCOUNT_PAGE = "/account"; // 账号管理
  static const String LINE_PAGE = "/line"; // 线路管理
  static const String WINDOWS_PAGE = "/windows"; // 界面管理
  static const String PRIVACY_PAGE = "/privacy"; // 隐私管理
  static const String CHAT_PAGE = "/chat"; // 聊天页面
  static const String PRIVATE_SESSION_DETAIL_PAGE = "/private_session_detail"; // 聊天信息
  static const String GROUP_SESSION_DETAIL_PAGE = "/group_session_detail"; // 聊天信息
  static const String SELECT_CONTACTS_PAGE = "/select_contacts"; // 选择联系人
  static const String SESSION_MEMBER_PAGE = "/session_member"; // 群成员
  static const String SESSION_MEMBERS_PAGE = "/session_members"; // 群成员管理
  static const String SESSION_MANAGER_PAGE = "/session_manager"; // 群管理
  static const String ADD_FRIEND_PAGE = "/add_friend"; // 添加好友
  static const String BLACKLIST_PAGE = "/blacklist"; // 黑名单
  static const String NEW_FRIEND_PAGE = "/new_friend"; // 黑名单
  static const String SESSIONS_PAGE = "/sessions"; // 群聊
  static const String MUTE_PAGE = "/mute"; // 群聊
  static const String PACKAGE_RESULT_PAGE = "/package_result"; // 红包结果
  static const String PACKAGE_PUBLISH_PAGE = "/publish_package"; // 发红包
  static const String MY_QR_CODE_PAGE = "/my_qr_code"; // 我的二维码
  static const String GOOGLE_VERIFY_PAGE = "/google_verify"; // 我的二维码
  static const String USER_INFO_PAGE = "/user_info"; // 用户信息
  static const String SESSION_SUP_ADMIN_PAGE = "/session_sup_admin"; // 群管理员
  static const String DEVICES_PAGE = "/devices"; // 设备
  static const String CHARGE_WAY_PAGE = "/charge_way"; // 设备
  static const String CHARGE_PAGE = "/charge"; // 设备
  static const String TRANSFER_PAGE = "/transfer"; // 转账
  static const String WALLET_PAGE = "/wallet"; // 钱包
  static const String ADD_CHARGE_WAY_PAGE = "/add_charge_way"; // 添加收款方式
  static const String NOTICE_SETTING_PAGE = "/notice_setting"; // 通知
  static const String CHAT_BACKGROUND_PAGE = "/chat_background"; // 聊天背景
  static const String FONT_SIZE_PAGE = "/font_size"; // 字体大小
  static const String PAY_PASSWORD_PAGE = "/pay_password"; // 支付密码
  static const String GESTURE_PASSWORD_PAGE = "/gesture_password"; // 手势密码
  static const String LOCK_SCREEN_PASSWORD_PAGE = "/lock_screen_password"; // 锁屏密码
}
